# Generated by Django 4.2 on 2023-04-25 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trip_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='if_finished',
        ),
    ]
